name: Flutter Release APK Build

on:
  push:
    branches: [main, master, release]
    tags:
      - 'v*'
  pull_request:
    branches: [main, master]
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    name: Build Android Release APK
    runs-on: ubuntu-latest
    permissions:
      contents: write # Explicitly set write permission for contents

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # Kept as requested
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4 # Updated version
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Create GitHub Release and Upload APK
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          draft: false
          prerelease: false
          # No GITHUB_TOKEN environment variable needed as permissions are already granted
